apiVersion: v1
kind: Namespace
metadata:
  name: movie-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckad-front
  namespace: frontend
  labels:
    app: ckad-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ckad-frontend
  template:
    metadata:
      labels:
        app: ckad-frontend
        name: ckad-frontend
    spec:
      containers:
        - name: ckad-frontend
          image: jalcina/ckad-front:latest
          env:
            - name: BACKEND_URL
              value: "movie-app-be:3000"
            - name: PORT
              value: "3030"
          ports:
            - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: ckad-backend-service
  namespace: ckad-backend
spec:
  loadBalancerIP: #{ServiceIP}#
  type: LoadBalancer
  ports:
    - name: http
      port: 3030
      targetPort: 3030
  selector:
    app: ckad-backend-service